---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/sistemas
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -a * $DEPLOYPATH/
    - /bin/cp -f .htaccess $DEPLOYPATH/ 2>/dev/null || true
