-- ==========================================================
-- BASE DE DATOS 100% LIMPIA PARA NUEVA AGENCIA
-- Estructura completa de tablas sin registros previos
-- Portal de Sistemas
-- ==========================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';

-- Eliminar tablas existentes si ya existieran
DROP TABLE IF EXISTS `usuario_permisos`;
DROP TABLE IF EXISTS `modulos`;
DROP TABLE IF EXISTS `usuarios`;
DROP TABLE IF EXISTS `agencia_areas`;
DROP TABLE IF EXISTS `agencias`;
DROP TABLE IF EXISTS `infra_diagramas`;
DROP TABLE IF EXISTS `infra_nodos`;
DROP TABLE IF EXISTS `infra_planos_2d`;
DROP TABLE IF EXISTS `infra_red_idf`;
DROP TABLE IF EXISTS `infra_site`;
DROP TABLE IF EXISTS `infra_switch_puertos`;
DROP TABLE IF EXISTS `infra_vlans`;
DROP TABLE IF EXISTS `inv_archivo`;
DROP TABLE IF EXISTS `inv_dispositivos_moviles`;
DROP TABLE IF EXISTS `inv_dvr_camaras`;
DROP TABLE IF EXISTS `inv_equipos_baja`;
DROP TABLE IF EXISTS `inv_equipos_corp`;
DROP TABLE IF EXISTS `inv_equipos_vw`;
DROP TABLE IF EXISTS `inv_licencias_office`;
DROP TABLE IF EXISTS `inv_monitores`;
DROP TABLE IF EXISTS `inv_nobreak_baja`;
DROP TABLE IF EXISTS `inv_site_vw`;
DROP TABLE IF EXISTS `inv_telefonos_poe`;
DROP TABLE IF EXISTS `tickets_soporte`;

-- --------------------------------------------------------
-- Tabla: `usuario_permisos` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `usuario_permisos` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `usuario_id` INT NULL,
  `modulo_clave` VARCHAR(50) NOT NULL,
  `puede_ver` INT DEFAULT 1,
  `puede_crear` INT DEFAULT 1,
  `puede_editar` INT DEFAULT 1,
  `puede_eliminar` INT DEFAULT 1,
  `puede_exportar` INT DEFAULT 1,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_usuario_permiso` (`usuario_id`, `modulo_clave`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `modulos` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `modulos` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `clave` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `descripcion` TEXT NULL,
  `icono` VARCHAR(50) NULL,
  `orden` INT DEFAULT 0,
  `estatus` INT DEFAULT 1,
  `creado_en` DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_modulos_clave` (`clave`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `usuarios` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `usuarios` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `usuario` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(255) NULL,
  `agencia` VARCHAR(100) NULL,
  `rol` VARCHAR(20) NULL,
  `activo` INT DEFAULT 1,
  `creado_en` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `acceso_portal` INT DEFAULT 1,
  `area` VARCHAR(100) NULL,
  `puesto` VARCHAR(100) NULL,
  `telefono` VARCHAR(50) NULL,
  `foto_url` VARCHAR(255) NULL,
  UNIQUE KEY `uq_usuarios_usuario` (`usuario`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `agencia_areas` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `agencia_areas` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `agencia_id` INT NULL,
  `nombre` VARCHAR(100) NULL,
  `estatus` INT DEFAULT 1,
  `creado_en` DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_agencia_area` (`agencia_id`, `nombre`(100))
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `agencias` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `agencias` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `nombre` VARCHAR(100) NULL,
  `razon_social` VARCHAR(150) NULL,
  `rfc` VARCHAR(20) NULL,
  `direccion` TEXT NULL,
  `encargado_sistemas` VARCHAR(100) NULL,
  `telefono_sistemas` VARCHAR(50) NULL,
  `correo_sistemas` VARCHAR(100) NULL,
  `logo_url` VARCHAR(255) NULL,
  `foto_url` VARCHAR(255) NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `maps_url` TEXT NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `infra_diagramas` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `infra_diagramas` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `titulo` TEXT NULL,
  `tipo` TEXT NULL,
  `version` TEXT NULL,
  `archivo_url` TEXT NULL,
  `descripcion` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `infra_nodos` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `infra_nodos` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `codigo_nodo` TEXT NULL,
  `tipo_nodo` TEXT NULL,
  `ubicacion` TEXT NULL,
  `patch_panel` TEXT NULL,
  `switch_puerto` TEXT NULL,
  `vlan` TEXT NULL,
  `estatus` TEXT NULL,
  `notas` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tiene_telefono_poe` INT DEFAULT 0,
  `telefono_poe_id` INT DEFAULT 0,
  `telefono_poe_info` TEXT NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `infra_planos_2d` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `infra_planos_2d` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `nombre_plano` TEXT NULL,
  `imagen_fondo_url` TEXT NULL,
  `ancho_canvas` INT DEFAULT 1200,
  `alto_canvas` INT DEFAULT 800,
  `elementos_json` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `infra_red_idf` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `infra_red_idf` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `nombre_idf` TEXT NULL,
  `ubicacion` TEXT NULL,
  `rango_ips` TEXT NULL,
  `vlans` TEXT NULL,
  `switch_principal` TEXT NULL,
  `no_puertos` TEXT NULL,
  `no_racks` TEXT NULL,
  `estatus` TEXT NULL,
  `foto_idf` TEXT NULL,
  `notas` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `infra_site` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `infra_site` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `nombre_site` TEXT NULL,
  `ubicacion` TEXT NULL,
  `tipo_espacio` TEXT NULL,
  `temperatura_objetivo` TEXT NULL,
  `aire_acondicionado` TEXT NULL,
  `btu` TEXT NULL,
  `aire_estatus` TEXT NULL,
  `ups_principal` TEXT NULL,
  `cap_ups` TEXT NULL,
  `planta_luz` TEXT NULL,
  `control_acceso` TEXT NULL,
  `contra_incendio` TEXT NULL,
  `foto_site` TEXT NULL,
  `observaciones` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `infra_switch_puertos` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `infra_switch_puertos` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `switch_key` TEXT NULL,
  `switch_nombre` TEXT NULL,
  `puerto_numero` INT NULL,
  `equipo_key` TEXT NULL,
  `equipo_nombre` TEXT NULL,
  `equipo_tipo` TEXT NULL,
  `equipo_ip` TEXT NULL,
  `nodo_codigo` TEXT NULL,
  `vlan` TEXT NULL,
  `estatus` TEXT NULL,
  `notas` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `tiene_telefono_poe` INT DEFAULT 0,
  `telefono_poe_key` TEXT NULL,
  `telefono_poe_nombre` TEXT NULL,
  `telefono_poe_ip` TEXT NULL,
  `telefono_poe_ext` TEXT NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `infra_vlans` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `infra_vlans` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `vlan_id` INT NULL,
  `nombre_vlan` TEXT NULL,
  `subred` TEXT NULL,
  `gateway` TEXT NULL,
  `dhcp_rango` TEXT NULL,
  `descripcion` TEXT NULL,
  `estatus` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `inv_archivo` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `inv_archivo` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `departamento` TEXT NULL,
  `puesto` TEXT NULL,
  `nombre` TEXT NULL,
  `monitor` TEXT NULL,
  `pulgadas` TEXT NULL,
  `serie` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `garantia2` TEXT NULL,
  `garantia` TEXT NULL,
  `contrasena_remoto` TEXT NULL,
  `contrasena_gds` TEXT NULL,
  `correo_oficial_planta` TEXT NULL,
  `motivo_baja` TEXT NULL,
  `puerto_patch_panel` TEXT NULL,
  `puerto_sw` TEXT NULL,
  `numero_nodo` TEXT NULL,
  `factura_url` TEXT NULL,
  `responsiva_url` TEXT NULL,
  `costo` TEXT NULL,
  `foto_equipo` TEXT NULL,
  `dvr_vinculado` TEXT NULL,
  `tipo_registro` TEXT NULL,
  `dias_grabacion` TEXT NULL,
  `usuario_dvr` TEXT NULL,
  `numero_discos` TEXT NULL,
  `canal_analogico` TEXT NULL,
  `canal_ip` TEXT NULL,
  `ubicacion` TEXT NULL,
  `foto_vista_camara` TEXT NULL,
  `subtipo_camara` TEXT NULL,
  `fabricante` TEXT NULL,
  `folio_factura` TEXT NULL,
  `mac_ethernet` TEXT NULL,
  `mac_wifi` TEXT NULL,
  `cantidad_puertos` TEXT NULL,
  `velocidad_puertos` TEXT NULL,
  `tipo_switch` TEXT NULL,
  `firmware_version` TEXT NULL,
  `posicion_rack` TEXT NULL,
  `sistema_op` TEXT NULL,
  `procesador` TEXT NULL,
  `ram` TEXT NULL,
  `almacenamiento` TEXT NULL,
  `cantidad_discos` TEXT NULL,
  `tipo_servidor` TEXT NULL,
  `funcion_servicio` TEXT NULL,
  `ambiente` TEXT NULL,
  `criticidad` TEXT NULL,
  `bahias_nas` TEXT NULL,
  `capacidad_disco_ind` TEXT NULL,
  `capacidad_disponible` TEXT NULL,
  `config_raid` TEXT NULL,
  `tipo_discos` TEXT NULL,
  `protocolos_nas` TEXT NULL,
  `proveedor` TEXT NULL,
  `tipo_enlace` TEXT NULL,
  `ancho_banda` TEXT NULL,
  `simetria_enlace` TEXT NULL,
  `tipo_conexion` TEXT NULL,
  `numero_contrato` TEXT NULL,
  `numero_cuenta` TEXT NULL,
  `circuit_id` TEXT NULL,
  `soporte_contacto` TEXT NULL,
  `ip_publica` TEXT NULL,
  `ip_local` TEXT NULL,
  `unifi_os_ver` TEXT NULL,
  `controller_ver` TEXT NULL,
  `velocidad_enlace` TEXT NULL,
  `ssids` TEXT NULL,
  `vlans` TEXT NULL,
  `poe` TEXT NULL,
  `controlador_ap` TEXT NULL,
  `capacidad_va` TEXT NULL,
  `capacidad_w` TEXT NULL,
  `tipo_ups` TEXT NULL,
  `voltaje_entrada` TEXT NULL,
  `voltaje_salida` TEXT NULL,
  `cant_baterias` TEXT NULL,
  `specs_baterias` TEXT NULL,
  `fecha_bateria` TEXT NULL,
  `autonomia` TEXT NULL,
  `imei_1` TEXT NULL,
  `imei_2` TEXT NULL,
  `numero_telefonico` TEXT NULL,
  `color` TEXT NULL,
  `accesorios` TEXT NULL,
  `fecha_asignacion` TEXT NULL,
  `tiene_plan_celular` TEXT NULL,
  `vencimiento_plan` TEXT NULL,
  `proveedor_plan` TEXT NULL,
  `numero_contrato_plan` TEXT NULL,
  `estado_fisico` TEXT NULL,
  `tamano_pantalla` TEXT NULL,
  `resolucion` TEXT NULL,
  `subtipo_dispositivo` TEXT NULL,
  `especificaciones` TEXT NULL,
  `observaciones` TEXT NULL,
  `marca` TEXT NULL,
  `modelo_exacto` TEXT NULL,
  `fecha_adquisicion` TEXT NULL,
  `contrato` TEXT NULL,
  `usuario_impresora` TEXT NULL,
  `contrasena_impresora` TEXT NULL,
  `usuario_impresora_web` TEXT NULL,
  `contrasena_impresora_web` TEXT NULL,
  `ip` TEXT NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `inv_dispositivos_moviles` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `inv_dispositivos_moviles` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `departamento` TEXT NULL,
  `puesto` TEXT NULL,
  `nombre` TEXT NULL,
  `tablet` TEXT NULL,
  `celular` TEXT NULL,
  `pantalla` TEXT NULL,
  `contrasena` TEXT NULL,
  `serie` TEXT NULL,
  `rom` TEXT NULL,
  `ram` TEXT NULL,
  `android` TEXT NULL,
  `mail` TEXT NULL,
  `mac` TEXT NULL,
  `plan` TEXT NULL,
  `factura` TEXT NULL,
  `fecha_compra` DATE NULL,
  `proveedor` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `garantia2` TEXT NULL,
  `garantia` TEXT NULL,
  `contrasena_remoto` TEXT NULL,
  `contrasena_gds` TEXT NULL,
  `correo_oficial_planta` TEXT NULL,
  `motivo_baja` TEXT NULL,
  `puerto_patch_panel` TEXT NULL,
  `puerto_sw` TEXT NULL,
  `numero_nodo` TEXT NULL,
  `factura_url` TEXT NULL,
  `responsiva_url` TEXT NULL,
  `costo` TEXT NULL,
  `foto_equipo` TEXT NULL,
  `dvr_vinculado` TEXT NULL,
  `tipo_registro` TEXT NULL,
  `dias_grabacion` TEXT NULL,
  `usuario_dvr` TEXT NULL,
  `numero_discos` TEXT NULL,
  `canal_analogico` TEXT NULL,
  `canal_ip` TEXT NULL,
  `ubicacion` TEXT NULL,
  `foto_vista_camara` TEXT NULL,
  `subtipo_camara` TEXT NULL,
  `fabricante` TEXT NULL,
  `folio_factura` TEXT NULL,
  `mac_ethernet` TEXT NULL,
  `mac_wifi` TEXT NULL,
  `cantidad_puertos` TEXT NULL,
  `velocidad_puertos` TEXT NULL,
  `tipo_switch` TEXT NULL,
  `firmware_version` TEXT NULL,
  `posicion_rack` TEXT NULL,
  `sistema_op` TEXT NULL,
  `procesador` TEXT NULL,
  `almacenamiento` TEXT NULL,
  `cantidad_discos` TEXT NULL,
  `tipo_servidor` TEXT NULL,
  `funcion_servicio` TEXT NULL,
  `ambiente` TEXT NULL,
  `criticidad` TEXT NULL,
  `bahias_nas` TEXT NULL,
  `capacidad_disco_ind` TEXT NULL,
  `capacidad_disponible` TEXT NULL,
  `config_raid` TEXT NULL,
  `tipo_discos` TEXT NULL,
  `protocolos_nas` TEXT NULL,
  `tipo_enlace` TEXT NULL,
  `ancho_banda` TEXT NULL,
  `simetria_enlace` TEXT NULL,
  `tipo_conexion` TEXT NULL,
  `numero_contrato` TEXT NULL,
  `numero_cuenta` TEXT NULL,
  `circuit_id` TEXT NULL,
  `soporte_contacto` TEXT NULL,
  `ip_publica` TEXT NULL,
  `ip_local` TEXT NULL,
  `unifi_os_ver` TEXT NULL,
  `controller_ver` TEXT NULL,
  `velocidad_enlace` TEXT NULL,
  `ssids` TEXT NULL,
  `vlans` TEXT NULL,
  `poe` TEXT NULL,
  `controlador_ap` TEXT NULL,
  `capacidad_va` TEXT NULL,
  `capacidad_w` TEXT NULL,
  `tipo_ups` TEXT NULL,
  `voltaje_entrada` TEXT NULL,
  `voltaje_salida` TEXT NULL,
  `cant_baterias` TEXT NULL,
  `specs_baterias` TEXT NULL,
  `fecha_bateria` TEXT NULL,
  `autonomia` TEXT NULL,
  `imei_1` TEXT NULL,
  `imei_2` TEXT NULL,
  `numero_telefonico` TEXT NULL,
  `color` TEXT NULL,
  `accesorios` TEXT NULL,
  `fecha_asignacion` TEXT NULL,
  `tiene_plan_celular` TEXT NULL,
  `vencimiento_plan` TEXT NULL,
  `proveedor_plan` TEXT NULL,
  `numero_contrato_plan` TEXT NULL,
  `estado_fisico` TEXT NULL,
  `tamano_pantalla` TEXT NULL,
  `resolucion` TEXT NULL,
  `subtipo_dispositivo` TEXT NULL,
  `especificaciones` TEXT NULL,
  `observaciones` TEXT NULL,
  `marca` TEXT NULL,
  `estatus` TEXT NULL,
  `modelo` TEXT NULL,
  `modelo_exacto` TEXT NULL,
  `fecha_adquisicion` TEXT NULL,
  `contrato` TEXT NULL,
  `usuario_impresora` TEXT NULL,
  `contrasena_impresora` TEXT NULL,
  `usuario_impresora_web` TEXT NULL,
  `contrasena_impresora_web` TEXT NULL,
  `ip` TEXT NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `inv_dvr_camaras` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `inv_dvr_camaras` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `camaras` TEXT NULL,
  `dvr` TEXT NULL,
  `ip` TEXT NULL,
  `numero_serie` TEXT NULL,
  `almacenamiento` TEXT NULL,
  `contrasena_dvr` TEXT NULL,
  `contrasena_camara` TEXT NULL,
  `cam_totales_ip` INT DEFAULT 0,
  `disponibles_ip` INT DEFAULT 0,
  `cam_totales_analogicas` INT DEFAULT 0,
  `disponibles` INT DEFAULT 0,
  `modelo` TEXT NULL,
  `nombre` TEXT NULL,
  `capacidad_actual` TEXT NULL,
  `cotizar` TEXT NULL,
  `maximo_por_disco` TEXT NULL,
  `capacidad_discos` TEXT NULL,
  `tiene_actual` TEXT NULL,
  `columna1` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `garantia2` TEXT NULL,
  `garantia` TEXT NULL,
  `contrasena_remoto` TEXT NULL,
  `contrasena_gds` TEXT NULL,
  `correo_oficial_planta` TEXT NULL,
  `motivo_baja` TEXT NULL,
  `puerto_patch_panel` TEXT NULL,
  `puerto_sw` TEXT NULL,
  `numero_nodo` TEXT NULL,
  `factura_url` TEXT NULL,
  `responsiva_url` TEXT NULL,
  `costo` TEXT NULL,
  `foto_equipo` TEXT NULL,
  `dvr_vinculado` TEXT NULL,
  `tipo_registro` TEXT NULL,
  `dias_grabacion` TEXT NULL,
  `usuario_dvr` TEXT NULL,
  `numero_discos` TEXT NULL,
  `canal_analogico` TEXT NULL,
  `canal_ip` TEXT NULL,
  `ubicacion` TEXT NULL,
  `foto_vista_camara` TEXT NULL,
  `subtipo_camara` TEXT NULL,
  `departamento` TEXT NULL,
  `fabricante` TEXT NULL,
  `folio_factura` TEXT NULL,
  `mac_ethernet` TEXT NULL,
  `mac_wifi` TEXT NULL,
  `cantidad_puertos` TEXT NULL,
  `velocidad_puertos` TEXT NULL,
  `tipo_switch` TEXT NULL,
  `firmware_version` TEXT NULL,
  `posicion_rack` TEXT NULL,
  `sistema_op` TEXT NULL,
  `procesador` TEXT NULL,
  `ram` TEXT NULL,
  `cantidad_discos` TEXT NULL,
  `tipo_servidor` TEXT NULL,
  `funcion_servicio` TEXT NULL,
  `ambiente` TEXT NULL,
  `criticidad` TEXT NULL,
  `bahias_nas` TEXT NULL,
  `capacidad_disco_ind` TEXT NULL,
  `capacidad_disponible` TEXT NULL,
  `config_raid` TEXT NULL,
  `tipo_discos` TEXT NULL,
  `protocolos_nas` TEXT NULL,
  `proveedor` TEXT NULL,
  `tipo_enlace` TEXT NULL,
  `ancho_banda` TEXT NULL,
  `simetria_enlace` TEXT NULL,
  `tipo_conexion` TEXT NULL,
  `numero_contrato` TEXT NULL,
  `numero_cuenta` TEXT NULL,
  `circuit_id` TEXT NULL,
  `soporte_contacto` TEXT NULL,
  `ip_publica` TEXT NULL,
  `ip_local` TEXT NULL,
  `unifi_os_ver` TEXT NULL,
  `controller_ver` TEXT NULL,
  `velocidad_enlace` TEXT NULL,
  `ssids` TEXT NULL,
  `vlans` TEXT NULL,
  `poe` TEXT NULL,
  `controlador_ap` TEXT NULL,
  `capacidad_va` TEXT NULL,
  `capacidad_w` TEXT NULL,
  `tipo_ups` TEXT NULL,
  `voltaje_entrada` TEXT NULL,
  `voltaje_salida` TEXT NULL,
  `cant_baterias` TEXT NULL,
  `specs_baterias` TEXT NULL,
  `fecha_bateria` TEXT NULL,
  `autonomia` TEXT NULL,
  `imei_1` TEXT NULL,
  `imei_2` TEXT NULL,
  `numero_telefonico` TEXT NULL,
  `color` TEXT NULL,
  `accesorios` TEXT NULL,
  `fecha_asignacion` TEXT NULL,
  `tiene_plan_celular` TEXT NULL,
  `vencimiento_plan` TEXT NULL,
  `proveedor_plan` TEXT NULL,
  `numero_contrato_plan` TEXT NULL,
  `estado_fisico` TEXT NULL,
  `tamano_pantalla` TEXT NULL,
  `resolucion` TEXT NULL,
  `subtipo_dispositivo` TEXT NULL,
  `especificaciones` TEXT NULL,
  `observaciones` TEXT NULL,
  `marca` TEXT NULL,
  `modelo_exacto` TEXT NULL,
  `fecha_adquisicion` TEXT NULL,
  `contrato` TEXT NULL,
  `usuario_impresora` TEXT NULL,
  `contrasena_impresora` TEXT NULL,
  `usuario_impresora_web` TEXT NULL,
  `contrasena_impresora_web` TEXT NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `inv_equipos_baja` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `inv_equipos_baja` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `departamento` TEXT NULL,
  `puesto` TEXT NULL,
  `usuario` TEXT NULL,
  `nombre_equipo` TEXT NULL,
  `estado` TEXT NULL,
  `tipo_equipo` TEXT NULL,
  `dominio` TEXT NULL,
  `logmein` TEXT NULL,
  `serie` TEXT NULL,
  `dd` TEXT NULL,
  `procesador` TEXT NULL,
  `ghz` TEXT NULL,
  `ram` TEXT NULL,
  `direccion_mac` TEXT NULL,
  `mac_wifi` TEXT NULL,
  `mac_ethernet` TEXT NULL,
  `sistema_op` TEXT NULL,
  `fecha_compra` DATE NULL,
  `folio_factura` TEXT NULL,
  `inicio_garantia` DATE NULL,
  `fin_garantia` DATE NULL,
  `garantia` TEXT NULL,
  `renovacion_equipo` TEXT NULL,
  `usuario_equipo` TEXT NULL,
  `contrasena` TEXT NULL,
  `office` TEXT NULL,
  `serie_office` TEXT NULL,
  `clave_candado` TEXT NULL,
  `gds` TEXT NULL,
  `correo` TEXT NULL,
  `correo_oficial_vw` TEXT NULL,
  `correo_oficial_seat` TEXT NULL,
  `extension` TEXT NULL,
  `compra` TEXT NULL,
  `proveedor` TEXT NULL,
  `antivirus` TEXT NULL,
  `dia_respaldo` TEXT NULL,
  `hora_respaldo` TEXT NULL,
  `no_break` TEXT NULL,
  `modelo_nobreak` TEXT NULL,
  `serie_nobreak` TEXT NULL,
  `expediente_completo` TEXT NULL,
  `columna1` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `contrasena_remoto` TEXT NULL,
  `contrasena_gds` TEXT NULL,
  `correo_oficial_planta` TEXT NULL,
  `motivo_baja` TEXT NULL,
  `garantia2` TEXT NULL,
  `puerto_patch_panel` TEXT NULL,
  `puerto_sw` TEXT NULL,
  `numero_nodo` TEXT NULL,
  `factura_url` TEXT NULL,
  `responsiva_url` TEXT NULL,
  `costo` TEXT NULL,
  `foto_equipo` TEXT NULL,
  `dvr_vinculado` TEXT NULL,
  `tipo_registro` TEXT NULL,
  `dias_grabacion` TEXT NULL,
  `usuario_dvr` TEXT NULL,
  `numero_discos` TEXT NULL,
  `canal_analogico` TEXT NULL,
  `canal_ip` TEXT NULL,
  `ubicacion` TEXT NULL,
  `foto_vista_camara` TEXT NULL,
  `subtipo_camara` TEXT NULL,
  `fabricante` TEXT NULL,
  `cantidad_puertos` TEXT NULL,
  `velocidad_puertos` TEXT NULL,
  `tipo_switch` TEXT NULL,
  `firmware_version` TEXT NULL,
  `posicion_rack` TEXT NULL,
  `almacenamiento` TEXT NULL,
  `cantidad_discos` TEXT NULL,
  `tipo_servidor` TEXT NULL,
  `funcion_servicio` TEXT NULL,
  `ambiente` TEXT NULL,
  `criticidad` TEXT NULL,
  `bahias_nas` TEXT NULL,
  `capacidad_disco_ind` TEXT NULL,
  `capacidad_disponible` TEXT NULL,
  `config_raid` TEXT NULL,
  `tipo_discos` TEXT NULL,
  `protocolos_nas` TEXT NULL,
  `tipo_enlace` TEXT NULL,
  `ancho_banda` TEXT NULL,
  `simetria_enlace` TEXT NULL,
  `tipo_conexion` TEXT NULL,
  `numero_contrato` TEXT NULL,
  `numero_cuenta` TEXT NULL,
  `circuit_id` TEXT NULL,
  `soporte_contacto` TEXT NULL,
  `ip_publica` TEXT NULL,
  `ip_local` TEXT NULL,
  `unifi_os_ver` TEXT NULL,
  `controller_ver` TEXT NULL,
  `velocidad_enlace` TEXT NULL,
  `ssids` TEXT NULL,
  `vlans` TEXT NULL,
  `poe` TEXT NULL,
  `controlador_ap` TEXT NULL,
  `capacidad_va` TEXT NULL,
  `capacidad_w` TEXT NULL,
  `tipo_ups` TEXT NULL,
  `voltaje_entrada` TEXT NULL,
  `voltaje_salida` TEXT NULL,
  `cant_baterias` TEXT NULL,
  `specs_baterias` TEXT NULL,
  `fecha_bateria` TEXT NULL,
  `autonomia` TEXT NULL,
  `imei_1` TEXT NULL,
  `imei_2` TEXT NULL,
  `numero_telefonico` TEXT NULL,
  `color` TEXT NULL,
  `accesorios` TEXT NULL,
  `fecha_asignacion` TEXT NULL,
  `tiene_plan_celular` TEXT NULL,
  `vencimiento_plan` TEXT NULL,
  `proveedor_plan` TEXT NULL,
  `numero_contrato_plan` TEXT NULL,
  `estado_fisico` TEXT NULL,
  `tamano_pantalla` TEXT NULL,
  `resolucion` TEXT NULL,
  `subtipo_dispositivo` TEXT NULL,
  `especificaciones` TEXT NULL,
  `observaciones` TEXT NULL,
  `marca` TEXT NULL,
  `modelo_exacto` TEXT NULL,
  `fecha_adquisicion` TEXT NULL,
  `contrato` TEXT NULL,
  `usuario_impresora` TEXT NULL,
  `contrasena_impresora` TEXT NULL,
  `usuario_impresora_web` TEXT NULL,
  `contrasena_impresora_web` TEXT NULL,
  `ip` TEXT NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `inv_equipos_corp` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `inv_equipos_corp` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `departamento` TEXT NULL,
  `puesto` TEXT NULL,
  `usuario` TEXT NULL,
  `nombre_equipo` TEXT NULL,
  `estado` TEXT NULL,
  `tipo_equipo` TEXT NULL,
  `dominio` TEXT NULL,
  `logmein` TEXT NULL,
  `serie` TEXT NULL,
  `dd` TEXT NULL,
  `procesador` TEXT NULL,
  `ghz` TEXT NULL,
  `ram` TEXT NULL,
  `direccion_mac` TEXT NULL,
  `mac_wifi` TEXT NULL,
  `mac_ethernet` TEXT NULL,
  `sistema_op` TEXT NULL,
  `fecha_compra` DATE NULL,
  `folio_factura` TEXT NULL,
  `inicio_garantia` DATE NULL,
  `fin_garantia` DATE NULL,
  `garantia` TEXT NULL,
  `renovacion_equipo` TEXT NULL,
  `usuario_equipo` TEXT NULL,
  `contrasena` TEXT NULL,
  `office` TEXT NULL,
  `serie_office` TEXT NULL,
  `clave_candado` TEXT NULL,
  `gds` TEXT NULL,
  `correo` TEXT NULL,
  `correo_oficial_vw` TEXT NULL,
  `correo_oficial_seat` TEXT NULL,
  `extension` TEXT NULL,
  `compra` TEXT NULL,
  `proveedor` TEXT NULL,
  `antivirus` TEXT NULL,
  `dia_respaldo` TEXT NULL,
  `hora_respaldo` TEXT NULL,
  `no_break` TEXT NULL,
  `modelo_nobreak` TEXT NULL,
  `serie_nobreak` TEXT NULL,
  `expediente_completo` TEXT NULL,
  `columna1` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `contrasena_remoto` TEXT NULL,
  `contrasena_gds` TEXT NULL,
  `correo_oficial_planta` TEXT NULL,
  `motivo_baja` TEXT NULL,
  `garantia2` TEXT NULL,
  `puerto_patch_panel` TEXT NULL,
  `puerto_sw` TEXT NULL,
  `numero_nodo` TEXT NULL,
  `factura_url` TEXT NULL,
  `responsiva_url` TEXT NULL,
  `costo` TEXT NULL,
  `foto_equipo` TEXT NULL,
  `dvr_vinculado` TEXT NULL,
  `tipo_registro` TEXT NULL,
  `dias_grabacion` TEXT NULL,
  `usuario_dvr` TEXT NULL,
  `numero_discos` TEXT NULL,
  `canal_analogico` TEXT NULL,
  `canal_ip` TEXT NULL,
  `ubicacion` TEXT NULL,
  `foto_vista_camara` TEXT NULL,
  `subtipo_camara` TEXT NULL,
  `fabricante` TEXT NULL,
  `cantidad_puertos` TEXT NULL,
  `velocidad_puertos` TEXT NULL,
  `tipo_switch` TEXT NULL,
  `firmware_version` TEXT NULL,
  `posicion_rack` TEXT NULL,
  `almacenamiento` TEXT NULL,
  `cantidad_discos` TEXT NULL,
  `tipo_servidor` TEXT NULL,
  `funcion_servicio` TEXT NULL,
  `ambiente` TEXT NULL,
  `criticidad` TEXT NULL,
  `bahias_nas` TEXT NULL,
  `capacidad_disco_ind` TEXT NULL,
  `capacidad_disponible` TEXT NULL,
  `config_raid` TEXT NULL,
  `tipo_discos` TEXT NULL,
  `protocolos_nas` TEXT NULL,
  `tipo_enlace` TEXT NULL,
  `ancho_banda` TEXT NULL,
  `simetria_enlace` TEXT NULL,
  `tipo_conexion` TEXT NULL,
  `numero_contrato` TEXT NULL,
  `numero_cuenta` TEXT NULL,
  `circuit_id` TEXT NULL,
  `soporte_contacto` TEXT NULL,
  `ip_publica` TEXT NULL,
  `ip_local` TEXT NULL,
  `unifi_os_ver` TEXT NULL,
  `controller_ver` TEXT NULL,
  `velocidad_enlace` TEXT NULL,
  `ssids` TEXT NULL,
  `vlans` TEXT NULL,
  `poe` TEXT NULL,
  `controlador_ap` TEXT NULL,
  `capacidad_va` TEXT NULL,
  `capacidad_w` TEXT NULL,
  `tipo_ups` TEXT NULL,
  `voltaje_entrada` TEXT NULL,
  `voltaje_salida` TEXT NULL,
  `cant_baterias` TEXT NULL,
  `specs_baterias` TEXT NULL,
  `fecha_bateria` TEXT NULL,
  `autonomia` TEXT NULL,
  `imei_1` TEXT NULL,
  `imei_2` TEXT NULL,
  `numero_telefonico` TEXT NULL,
  `color` TEXT NULL,
  `accesorios` TEXT NULL,
  `fecha_asignacion` TEXT NULL,
  `tiene_plan_celular` TEXT NULL,
  `vencimiento_plan` TEXT NULL,
  `proveedor_plan` TEXT NULL,
  `numero_contrato_plan` TEXT NULL,
  `estado_fisico` TEXT NULL,
  `tamano_pantalla` TEXT NULL,
  `resolucion` TEXT NULL,
  `subtipo_dispositivo` TEXT NULL,
  `especificaciones` TEXT NULL,
  `observaciones` TEXT NULL,
  `marca` TEXT NULL,
  `modelo_exacto` TEXT NULL,
  `fecha_adquisicion` TEXT NULL,
  `contrato` TEXT NULL,
  `usuario_impresora` TEXT NULL,
  `contrasena_impresora` TEXT NULL,
  `usuario_impresora_web` TEXT NULL,
  `contrasena_impresora_web` TEXT NULL,
  `ip` TEXT NULL,
  `switch_nombre` TEXT NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `inv_equipos_vw` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `inv_equipos_vw` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `departamento` TEXT NULL,
  `puesto` TEXT NULL,
  `usuario` TEXT NULL,
  `nombre_equipo` TEXT NULL,
  `estado` TEXT NULL,
  `tipo_equipo` TEXT NULL,
  `expediente_completo` TEXT NULL,
  `dominio` TEXT NULL,
  `logmein` TEXT NULL,
  `serie` TEXT NULL,
  `dd` TEXT NULL,
  `procesador` TEXT NULL,
  `ghz` TEXT NULL,
  `ram` TEXT NULL,
  `direccion_mac` TEXT NULL,
  `mac_wifi` TEXT NULL,
  `mac_ethernet` TEXT NULL,
  `sistema_op` TEXT NULL,
  `fecha_compra` DATE NULL,
  `folio_factura` TEXT NULL,
  `inicio_garantia` DATE NULL,
  `fin_garantia` DATE NULL,
  `garantia2` TEXT NULL,
  `renovacion_equipo` TEXT NULL,
  `usuario_equipo_dominio` TEXT NULL,
  `contrasena` TEXT NULL,
  `office` TEXT NULL,
  `serie_office` TEXT NULL,
  `clave_candado` TEXT NULL,
  `gds` TEXT NULL,
  `por_usuario` TEXT NULL,
  `equipo` TEXT NULL,
  `remoto` TEXT NULL,
  `usuario_gds` TEXT NULL,
  `correo` TEXT NULL,
  `correo_oficial_vw` TEXT NULL,
  `correo_oficial_seat` TEXT NULL,
  `extension` TEXT NULL,
  `power_pb` TEXT NULL,
  `contrasena_pb` TEXT NULL,
  `poc` TEXT NULL,
  `contrasena_poc` TEXT NULL,
  `msqp` TEXT NULL,
  `contrasena_msqp` TEXT NULL,
  `grp` TEXT NULL,
  `contrasena_grp` TEXT NULL,
  `etka` TEXT NULL,
  `contrasena_etka` TEXT NULL,
  `facebook` TEXT NULL,
  `contrasena_facebook` TEXT NULL,
  `instagram` TEXT NULL,
  `contrasena_instagram` TEXT NULL,
  `wish` TEXT NULL,
  `contrasena_wish` TEXT NULL,
  `marketing_cloud` TEXT NULL,
  `contrasena_marketing_cloud` TEXT NULL,
  `sales_cloud_force` TEXT NULL,
  `contrasena_sales_cloud_force` TEXT NULL,
  `pagina_la_villa` TEXT NULL,
  `contrasena_pagina_la_villa` TEXT NULL,
  `urban_science` TEXT NULL,
  `contrasena_urban_science` TEXT NULL,
  `canva` TEXT NULL,
  `contrasena_canva` TEXT NULL,
  `cuenta_integral` TEXT NULL,
  `contrasena_cuenta_integral` TEXT NULL,
  `compra` TEXT NULL,
  `proveedor` TEXT NULL,
  `antivirus` TEXT NULL,
  `dia_respaldo` TEXT NULL,
  `hora_respaldo` TEXT NULL,
  `no_break` TEXT NULL,
  `modelo_nobreak` TEXT NULL,
  `serie_nobreak` TEXT NULL,
  `columna1` TEXT NULL,
  `columna2` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `contrasena_remoto` TEXT NULL,
  `contrasena_gds` TEXT NULL,
  `correo_oficial_planta` TEXT NULL,
  `motivo_baja` TEXT NULL,
  `garantia` TEXT NULL,
  `puerto_patch_panel` TEXT NULL,
  `puerto_sw` TEXT NULL,
  `numero_nodo` TEXT NULL,
  `factura_url` TEXT NULL,
  `responsiva_url` TEXT NULL,
  `costo` TEXT NULL,
  `foto_equipo` TEXT NULL,
  `dvr_vinculado` TEXT NULL,
  `tipo_registro` TEXT NULL,
  `dias_grabacion` TEXT NULL,
  `usuario_dvr` TEXT NULL,
  `numero_discos` TEXT NULL,
  `canal_analogico` TEXT NULL,
  `canal_ip` TEXT NULL,
  `ubicacion` TEXT NULL,
  `foto_vista_camara` TEXT NULL,
  `subtipo_camara` TEXT NULL,
  `fabricante` TEXT NULL,
  `cantidad_puertos` TEXT NULL,
  `velocidad_puertos` TEXT NULL,
  `tipo_switch` TEXT NULL,
  `firmware_version` TEXT NULL,
  `posicion_rack` TEXT NULL,
  `almacenamiento` TEXT NULL,
  `cantidad_discos` TEXT NULL,
  `tipo_servidor` TEXT NULL,
  `funcion_servicio` TEXT NULL,
  `ambiente` TEXT NULL,
  `criticidad` TEXT NULL,
  `bahias_nas` TEXT NULL,
  `capacidad_disco_ind` TEXT NULL,
  `capacidad_disponible` TEXT NULL,
  `config_raid` TEXT NULL,
  `tipo_discos` TEXT NULL,
  `protocolos_nas` TEXT NULL,
  `tipo_enlace` TEXT NULL,
  `ancho_banda` TEXT NULL,
  `simetria_enlace` TEXT NULL,
  `tipo_conexion` TEXT NULL,
  `numero_contrato` TEXT NULL,
  `numero_cuenta` TEXT NULL,
  `circuit_id` TEXT NULL,
  `soporte_contacto` TEXT NULL,
  `ip_publica` TEXT NULL,
  `ip_local` TEXT NULL,
  `unifi_os_ver` TEXT NULL,
  `controller_ver` TEXT NULL,
  `velocidad_enlace` TEXT NULL,
  `ssids` TEXT NULL,
  `vlans` TEXT NULL,
  `poe` TEXT NULL,
  `controlador_ap` TEXT NULL,
  `capacidad_va` TEXT NULL,
  `capacidad_w` TEXT NULL,
  `tipo_ups` TEXT NULL,
  `voltaje_entrada` TEXT NULL,
  `voltaje_salida` TEXT NULL,
  `cant_baterias` TEXT NULL,
  `specs_baterias` TEXT NULL,
  `fecha_bateria` TEXT NULL,
  `autonomia` TEXT NULL,
  `imei_1` TEXT NULL,
  `imei_2` TEXT NULL,
  `numero_telefonico` TEXT NULL,
  `color` TEXT NULL,
  `accesorios` TEXT NULL,
  `fecha_asignacion` TEXT NULL,
  `tiene_plan_celular` TEXT NULL,
  `vencimiento_plan` TEXT NULL,
  `proveedor_plan` TEXT NULL,
  `numero_contrato_plan` TEXT NULL,
  `estado_fisico` TEXT NULL,
  `tamano_pantalla` TEXT NULL,
  `resolucion` TEXT NULL,
  `subtipo_dispositivo` TEXT NULL,
  `especificaciones` TEXT NULL,
  `observaciones` TEXT NULL,
  `marca` TEXT NULL,
  `modelo_exacto` TEXT NULL,
  `fecha_adquisicion` TEXT NULL,
  `contrato` TEXT NULL,
  `usuario_impresora` TEXT NULL,
  `contrasena_impresora` TEXT NULL,
  `usuario_impresora_web` TEXT NULL,
  `contrasena_impresora_web` TEXT NULL,
  `ip` TEXT NULL,
  `switch_nombre` TEXT NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `inv_licencias_office` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `inv_licencias_office` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `licencia` TEXT NULL,
  `area` TEXT NULL,
  `puesto` TEXT NULL,
  `nombre` TEXT NULL,
  `serie_equipo` TEXT NULL,
  `nombre_equipo` TEXT NULL,
  `serie_licencia` TEXT NULL,
  `factura` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `garantia2` TEXT NULL,
  `garantia` TEXT NULL,
  `contrasena_remoto` TEXT NULL,
  `contrasena_gds` TEXT NULL,
  `correo_oficial_planta` TEXT NULL,
  `motivo_baja` TEXT NULL,
  `puerto_patch_panel` TEXT NULL,
  `puerto_sw` TEXT NULL,
  `numero_nodo` TEXT NULL,
  `factura_url` TEXT NULL,
  `responsiva_url` TEXT NULL,
  `costo` TEXT NULL,
  `foto_equipo` TEXT NULL,
  `dvr_vinculado` TEXT NULL,
  `tipo_registro` TEXT NULL,
  `dias_grabacion` TEXT NULL,
  `usuario_dvr` TEXT NULL,
  `numero_discos` TEXT NULL,
  `canal_analogico` TEXT NULL,
  `canal_ip` TEXT NULL,
  `ubicacion` TEXT NULL,
  `foto_vista_camara` TEXT NULL,
  `subtipo_camara` TEXT NULL,
  `fabricante` TEXT NULL,
  `folio_factura` TEXT NULL,
  `mac_ethernet` TEXT NULL,
  `mac_wifi` TEXT NULL,
  `cantidad_puertos` TEXT NULL,
  `velocidad_puertos` TEXT NULL,
  `tipo_switch` TEXT NULL,
  `firmware_version` TEXT NULL,
  `posicion_rack` TEXT NULL,
  `sistema_op` TEXT NULL,
  `procesador` TEXT NULL,
  `ram` TEXT NULL,
  `almacenamiento` TEXT NULL,
  `cantidad_discos` TEXT NULL,
  `tipo_servidor` TEXT NULL,
  `funcion_servicio` TEXT NULL,
  `ambiente` TEXT NULL,
  `criticidad` TEXT NULL,
  `bahias_nas` TEXT NULL,
  `capacidad_disco_ind` TEXT NULL,
  `capacidad_disponible` TEXT NULL,
  `config_raid` TEXT NULL,
  `tipo_discos` TEXT NULL,
  `protocolos_nas` TEXT NULL,
  `proveedor` TEXT NULL,
  `tipo_enlace` TEXT NULL,
  `ancho_banda` TEXT NULL,
  `simetria_enlace` TEXT NULL,
  `tipo_conexion` TEXT NULL,
  `numero_contrato` TEXT NULL,
  `numero_cuenta` TEXT NULL,
  `circuit_id` TEXT NULL,
  `soporte_contacto` TEXT NULL,
  `ip_publica` TEXT NULL,
  `ip_local` TEXT NULL,
  `unifi_os_ver` TEXT NULL,
  `controller_ver` TEXT NULL,
  `velocidad_enlace` TEXT NULL,
  `ssids` TEXT NULL,
  `vlans` TEXT NULL,
  `poe` TEXT NULL,
  `controlador_ap` TEXT NULL,
  `capacidad_va` TEXT NULL,
  `capacidad_w` TEXT NULL,
  `tipo_ups` TEXT NULL,
  `voltaje_entrada` TEXT NULL,
  `voltaje_salida` TEXT NULL,
  `cant_baterias` TEXT NULL,
  `specs_baterias` TEXT NULL,
  `fecha_bateria` TEXT NULL,
  `autonomia` TEXT NULL,
  `imei_1` TEXT NULL,
  `imei_2` TEXT NULL,
  `numero_telefonico` TEXT NULL,
  `color` TEXT NULL,
  `accesorios` TEXT NULL,
  `fecha_asignacion` TEXT NULL,
  `tiene_plan_celular` TEXT NULL,
  `vencimiento_plan` TEXT NULL,
  `proveedor_plan` TEXT NULL,
  `numero_contrato_plan` TEXT NULL,
  `estado_fisico` TEXT NULL,
  `tamano_pantalla` TEXT NULL,
  `resolucion` TEXT NULL,
  `subtipo_dispositivo` TEXT NULL,
  `especificaciones` TEXT NULL,
  `observaciones` TEXT NULL,
  `marca` TEXT NULL,
  `modelo_exacto` TEXT NULL,
  `fecha_adquisicion` TEXT NULL,
  `contrato` TEXT NULL,
  `usuario_impresora` TEXT NULL,
  `contrasena_impresora` TEXT NULL,
  `usuario_impresora_web` TEXT NULL,
  `contrasena_impresora_web` TEXT NULL,
  `ip` TEXT NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `inv_monitores` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `inv_monitores` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `departamento` TEXT NULL,
  `puesto` TEXT NULL,
  `nombre` TEXT NULL,
  `monitor` TEXT NULL,
  `pulgadas` TEXT NULL,
  `serie` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `garantia2` TEXT NULL,
  `garantia` TEXT NULL,
  `contrasena_remoto` TEXT NULL,
  `contrasena_gds` TEXT NULL,
  `correo_oficial_planta` TEXT NULL,
  `motivo_baja` TEXT NULL,
  `puerto_patch_panel` TEXT NULL,
  `puerto_sw` TEXT NULL,
  `numero_nodo` TEXT NULL,
  `factura_url` TEXT NULL,
  `responsiva_url` TEXT NULL,
  `costo` TEXT NULL,
  `foto_equipo` TEXT NULL,
  `dvr_vinculado` TEXT NULL,
  `tipo_registro` TEXT NULL,
  `dias_grabacion` TEXT NULL,
  `usuario_dvr` TEXT NULL,
  `numero_discos` TEXT NULL,
  `canal_analogico` TEXT NULL,
  `canal_ip` TEXT NULL,
  `ubicacion` TEXT NULL,
  `foto_vista_camara` TEXT NULL,
  `subtipo_camara` TEXT NULL,
  `fabricante` TEXT NULL,
  `folio_factura` TEXT NULL,
  `mac_ethernet` TEXT NULL,
  `mac_wifi` TEXT NULL,
  `cantidad_puertos` TEXT NULL,
  `velocidad_puertos` TEXT NULL,
  `tipo_switch` TEXT NULL,
  `firmware_version` TEXT NULL,
  `posicion_rack` TEXT NULL,
  `sistema_op` TEXT NULL,
  `procesador` TEXT NULL,
  `ram` TEXT NULL,
  `almacenamiento` TEXT NULL,
  `cantidad_discos` TEXT NULL,
  `tipo_servidor` TEXT NULL,
  `funcion_servicio` TEXT NULL,
  `ambiente` TEXT NULL,
  `criticidad` TEXT NULL,
  `bahias_nas` TEXT NULL,
  `capacidad_disco_ind` TEXT NULL,
  `capacidad_disponible` TEXT NULL,
  `config_raid` TEXT NULL,
  `tipo_discos` TEXT NULL,
  `protocolos_nas` TEXT NULL,
  `proveedor` TEXT NULL,
  `tipo_enlace` TEXT NULL,
  `ancho_banda` TEXT NULL,
  `simetria_enlace` TEXT NULL,
  `tipo_conexion` TEXT NULL,
  `numero_contrato` TEXT NULL,
  `numero_cuenta` TEXT NULL,
  `circuit_id` TEXT NULL,
  `soporte_contacto` TEXT NULL,
  `ip_publica` TEXT NULL,
  `ip_local` TEXT NULL,
  `unifi_os_ver` TEXT NULL,
  `controller_ver` TEXT NULL,
  `velocidad_enlace` TEXT NULL,
  `ssids` TEXT NULL,
  `vlans` TEXT NULL,
  `poe` TEXT NULL,
  `controlador_ap` TEXT NULL,
  `capacidad_va` TEXT NULL,
  `capacidad_w` TEXT NULL,
  `tipo_ups` TEXT NULL,
  `voltaje_entrada` TEXT NULL,
  `voltaje_salida` TEXT NULL,
  `cant_baterias` TEXT NULL,
  `specs_baterias` TEXT NULL,
  `fecha_bateria` TEXT NULL,
  `autonomia` TEXT NULL,
  `imei_1` TEXT NULL,
  `imei_2` TEXT NULL,
  `numero_telefonico` TEXT NULL,
  `color` TEXT NULL,
  `accesorios` TEXT NULL,
  `fecha_asignacion` TEXT NULL,
  `tiene_plan_celular` TEXT NULL,
  `vencimiento_plan` TEXT NULL,
  `proveedor_plan` TEXT NULL,
  `numero_contrato_plan` TEXT NULL,
  `estado_fisico` TEXT NULL,
  `tamano_pantalla` TEXT NULL,
  `resolucion` TEXT NULL,
  `subtipo_dispositivo` TEXT NULL,
  `especificaciones` TEXT NULL,
  `observaciones` TEXT NULL,
  `marca` TEXT NULL,
  `modelo_exacto` TEXT NULL,
  `fecha_adquisicion` TEXT NULL,
  `contrato` TEXT NULL,
  `usuario_impresora` TEXT NULL,
  `contrasena_impresora` TEXT NULL,
  `usuario_impresora_web` TEXT NULL,
  `contrasena_impresora_web` TEXT NULL,
  `ip` TEXT NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `inv_nobreak_baja` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `inv_nobreak_baja` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `departamento` TEXT NULL,
  `puesto` TEXT NULL,
  `usuario` TEXT NULL,
  `nombre_equipo` TEXT NULL,
  `estado` TEXT NULL,
  `modelo` TEXT NULL,
  `serie_equipo` TEXT NULL,
  `modelo_nobreak` TEXT NULL,
  `serie_nobreak` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `contrasena_remoto` TEXT NULL,
  `contrasena_gds` TEXT NULL,
  `correo_oficial_planta` TEXT NULL,
  `motivo_baja` TEXT NULL,
  `garantia2` TEXT NULL,
  `garantia` TEXT NULL,
  `puerto_patch_panel` TEXT NULL,
  `puerto_sw` TEXT NULL,
  `numero_nodo` TEXT NULL,
  `factura_url` TEXT NULL,
  `responsiva_url` TEXT NULL,
  `costo` TEXT NULL,
  `foto_equipo` TEXT NULL,
  `dvr_vinculado` TEXT NULL,
  `tipo_registro` TEXT NULL,
  `dias_grabacion` TEXT NULL,
  `usuario_dvr` TEXT NULL,
  `numero_discos` TEXT NULL,
  `canal_analogico` TEXT NULL,
  `canal_ip` TEXT NULL,
  `ubicacion` TEXT NULL,
  `foto_vista_camara` TEXT NULL,
  `subtipo_camara` TEXT NULL,
  `fabricante` TEXT NULL,
  `folio_factura` TEXT NULL,
  `mac_ethernet` TEXT NULL,
  `mac_wifi` TEXT NULL,
  `cantidad_puertos` TEXT NULL,
  `velocidad_puertos` TEXT NULL,
  `tipo_switch` TEXT NULL,
  `firmware_version` TEXT NULL,
  `posicion_rack` TEXT NULL,
  `sistema_op` TEXT NULL,
  `procesador` TEXT NULL,
  `ram` TEXT NULL,
  `almacenamiento` TEXT NULL,
  `cantidad_discos` TEXT NULL,
  `tipo_servidor` TEXT NULL,
  `funcion_servicio` TEXT NULL,
  `ambiente` TEXT NULL,
  `criticidad` TEXT NULL,
  `bahias_nas` TEXT NULL,
  `capacidad_disco_ind` TEXT NULL,
  `capacidad_disponible` TEXT NULL,
  `config_raid` TEXT NULL,
  `tipo_discos` TEXT NULL,
  `protocolos_nas` TEXT NULL,
  `proveedor` TEXT NULL,
  `tipo_enlace` TEXT NULL,
  `ancho_banda` TEXT NULL,
  `simetria_enlace` TEXT NULL,
  `tipo_conexion` TEXT NULL,
  `numero_contrato` TEXT NULL,
  `numero_cuenta` TEXT NULL,
  `circuit_id` TEXT NULL,
  `soporte_contacto` TEXT NULL,
  `ip_publica` TEXT NULL,
  `ip_local` TEXT NULL,
  `unifi_os_ver` TEXT NULL,
  `controller_ver` TEXT NULL,
  `velocidad_enlace` TEXT NULL,
  `ssids` TEXT NULL,
  `vlans` TEXT NULL,
  `poe` TEXT NULL,
  `controlador_ap` TEXT NULL,
  `capacidad_va` TEXT NULL,
  `capacidad_w` TEXT NULL,
  `tipo_ups` TEXT NULL,
  `voltaje_entrada` TEXT NULL,
  `voltaje_salida` TEXT NULL,
  `cant_baterias` TEXT NULL,
  `specs_baterias` TEXT NULL,
  `fecha_bateria` TEXT NULL,
  `autonomia` TEXT NULL,
  `imei_1` TEXT NULL,
  `imei_2` TEXT NULL,
  `numero_telefonico` TEXT NULL,
  `color` TEXT NULL,
  `accesorios` TEXT NULL,
  `fecha_asignacion` TEXT NULL,
  `tiene_plan_celular` TEXT NULL,
  `vencimiento_plan` TEXT NULL,
  `proveedor_plan` TEXT NULL,
  `numero_contrato_plan` TEXT NULL,
  `estado_fisico` TEXT NULL,
  `tamano_pantalla` TEXT NULL,
  `resolucion` TEXT NULL,
  `subtipo_dispositivo` TEXT NULL,
  `especificaciones` TEXT NULL,
  `observaciones` TEXT NULL,
  `marca` TEXT NULL,
  `modelo_exacto` TEXT NULL,
  `fecha_adquisicion` TEXT NULL,
  `contrato` TEXT NULL,
  `usuario_impresora` TEXT NULL,
  `contrasena_impresora` TEXT NULL,
  `usuario_impresora_web` TEXT NULL,
  `contrasena_impresora_web` TEXT NULL,
  `ip` TEXT NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `inv_site_vw` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `inv_site_vw` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `departamento` TEXT NULL,
  `puesto` TEXT NULL,
  `usuario` TEXT NULL,
  `nombre_equipo` TEXT NULL,
  `estado` TEXT NULL,
  `equipo` TEXT NULL,
  `modelo` TEXT NULL,
  `serie` TEXT NULL,
  `fecha_compra` DATE NULL,
  `folio_factura` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `garantia2` TEXT NULL,
  `garantia` TEXT NULL,
  `contrasena_remoto` TEXT NULL,
  `contrasena_gds` TEXT NULL,
  `correo_oficial_planta` TEXT NULL,
  `motivo_baja` TEXT NULL,
  `puerto_patch_panel` TEXT NULL,
  `puerto_sw` TEXT NULL,
  `numero_nodo` TEXT NULL,
  `factura_url` TEXT NULL,
  `responsiva_url` TEXT NULL,
  `costo` TEXT NULL,
  `foto_equipo` TEXT NULL,
  `dvr_vinculado` TEXT NULL,
  `tipo_registro` TEXT NULL,
  `dias_grabacion` TEXT NULL,
  `usuario_dvr` TEXT NULL,
  `numero_discos` TEXT NULL,
  `canal_analogico` TEXT NULL,
  `canal_ip` TEXT NULL,
  `ubicacion` TEXT NULL,
  `foto_vista_camara` TEXT NULL,
  `subtipo_camara` TEXT NULL,
  `fabricante` TEXT NULL,
  `mac_ethernet` TEXT NULL,
  `mac_wifi` TEXT NULL,
  `cantidad_puertos` TEXT NULL,
  `velocidad_puertos` TEXT NULL,
  `tipo_switch` TEXT NULL,
  `firmware_version` TEXT NULL,
  `posicion_rack` TEXT NULL,
  `sistema_op` TEXT NULL,
  `procesador` TEXT NULL,
  `ram` TEXT NULL,
  `almacenamiento` TEXT NULL,
  `cantidad_discos` TEXT NULL,
  `tipo_servidor` TEXT NULL,
  `funcion_servicio` TEXT NULL,
  `ambiente` TEXT NULL,
  `criticidad` TEXT NULL,
  `bahias_nas` TEXT NULL,
  `capacidad_disco_ind` TEXT NULL,
  `capacidad_disponible` TEXT NULL,
  `config_raid` TEXT NULL,
  `tipo_discos` TEXT NULL,
  `protocolos_nas` TEXT NULL,
  `proveedor` TEXT NULL,
  `tipo_enlace` TEXT NULL,
  `ancho_banda` TEXT NULL,
  `simetria_enlace` TEXT NULL,
  `tipo_conexion` TEXT NULL,
  `numero_contrato` TEXT NULL,
  `numero_cuenta` TEXT NULL,
  `circuit_id` TEXT NULL,
  `soporte_contacto` TEXT NULL,
  `ip_publica` TEXT NULL,
  `ip_local` TEXT NULL,
  `unifi_os_ver` TEXT NULL,
  `controller_ver` TEXT NULL,
  `velocidad_enlace` TEXT NULL,
  `ssids` TEXT NULL,
  `vlans` TEXT NULL,
  `poe` TEXT NULL,
  `controlador_ap` TEXT NULL,
  `capacidad_va` TEXT NULL,
  `capacidad_w` TEXT NULL,
  `tipo_ups` TEXT NULL,
  `voltaje_entrada` TEXT NULL,
  `voltaje_salida` TEXT NULL,
  `cant_baterias` TEXT NULL,
  `specs_baterias` TEXT NULL,
  `fecha_bateria` TEXT NULL,
  `autonomia` TEXT NULL,
  `imei_1` TEXT NULL,
  `imei_2` TEXT NULL,
  `numero_telefonico` TEXT NULL,
  `color` TEXT NULL,
  `accesorios` TEXT NULL,
  `fecha_asignacion` TEXT NULL,
  `tiene_plan_celular` TEXT NULL,
  `vencimiento_plan` TEXT NULL,
  `proveedor_plan` TEXT NULL,
  `numero_contrato_plan` TEXT NULL,
  `estado_fisico` TEXT NULL,
  `tamano_pantalla` TEXT NULL,
  `resolucion` TEXT NULL,
  `subtipo_dispositivo` TEXT NULL,
  `especificaciones` TEXT NULL,
  `observaciones` TEXT NULL,
  `marca` TEXT NULL,
  `ip` TEXT NULL,
  `contrasena` TEXT NULL,
  `modelo_exacto` TEXT NULL,
  `fecha_adquisicion` TEXT NULL,
  `contrato` TEXT NULL,
  `usuario_impresora` TEXT NULL,
  `contrasena_impresora` TEXT NULL,
  `usuario_impresora_web` TEXT NULL,
  `contrasena_impresora_web` TEXT NULL,
  `switch_nombre` TEXT NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `inv_telefonos_poe` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `inv_telefonos_poe` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `extension` TEXT NULL,
  `usuario` TEXT NULL,
  `departamento` TEXT NULL,
  `puesto` TEXT NULL,
  `ubicacion` TEXT NULL,
  `estado` TEXT NULL,
  `marca` TEXT NULL,
  `modelo` TEXT NULL,
  `serie` TEXT NULL,
  `mac` TEXT NULL,
  `ip` TEXT NULL,
  `tipo_poe` TEXT NULL,
  `numero_nodo` TEXT NULL,
  `puerto_patch_panel` TEXT NULL,
  `puerto_sw` TEXT NULL,
  `switch_nombre` TEXT NULL,
  `vlan` TEXT NULL,
  `servidor_sip` TEXT NULL,
  `contrasena_web` TEXT NULL,
  `costo` TEXT NULL,
  `fecha_compra` TEXT NULL,
  `folio_factura` TEXT NULL,
  `proveedor` TEXT NULL,
  `observaciones` TEXT NULL,
  `foto_equipo` TEXT NULL,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `area` TEXT NULL,
  `numero_telefonico` TEXT NULL,
  `tipo_licencia` TEXT NULL,
  `correo` TEXT NULL,
  `portabilidad` TEXT NULL,
  `factura_url` TEXT NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Tabla: `tickets_soporte` (Estructura vacía)
-- --------------------------------------------------------
CREATE TABLE `tickets_soporte` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `folio` VARCHAR(50),
  `area_sistemas` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `prioridad` VARCHAR(50) DEFAULT 'Media',
  `estado` VARCHAR(50) DEFAULT 'Abierto',
  `solicitante_id` INT NULL,
  `solicitante_usuario` VARCHAR(100) NULL,
  `solicitante_nombre` VARCHAR(150),
  `solicitante_email` VARCHAR(150),
  `solicitante_agencia` VARCHAR(100),
  `asignado_a` VARCHAR(150),
  `archivo_adjunto` VARCHAR(255),
  `notas_resolucion` TEXT,
  `creado_en` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==========================================================
-- REGISTROS BASE MÍNIMOS INDISPENSABLES
-- (Solo catálogo de módulos y 1 usuario administrador inicial)
-- ==========================================================

-- 1. Catálogo oficial de Módulos del Sistema
INSERT INTO `modulos` (`id`, `clave`, `nombre`, `descripcion`, `icono`, `orden`, `estatus`, `creado_en`) VALUES
(1, 'usuarios', 'Gestión de Usuarios', 'Administración de usuarios, roles y permisos', 'bi-people-fill', 1, 1, NOW()),
(2, 'ordenes_servicio', 'Órdenes de Servicio', 'Resumen de órdenes abiertas, cerradas y montos', 'bi-file-earmark-bar-graph', 2, 1, NOW()),
(3, 'equipos', 'Inventario de Equipos', 'Control de PCs, laptops, servidores e impresoras', 'bi-display-fill', 3, 1, NOW()),
(4, 'celulares', 'Inventario de Celulares', 'Control de equipos móviles y líneas', 'bi-phone-fill', 4, 1, NOW()),
(5, 'licencias', 'Licencias de Software', 'Matriz de licenciamiento corporativo', 'bi-key-fill', 5, 1, NOW()),
(6, 'infraestructura', 'Infraestructura (SITE / IDF)', 'Control de racks y cableado', 'bi-hdd-rack-fill', 6, 1, NOW());

-- 2. Usuario Administrador Inicial para Primer Acceso
-- Usuario: admin | Contraseña inicial: Admin123!
INSERT INTO `usuarios` (`id`, `usuario`, `nombre`, `email`, `password`, `agencia`, `rol`, `activo`, `acceso_portal`) VALUES
(1, 'admin', 'Administrador de Sistemas', 'admin@agencia.com', '$2y$10$e7mEXpv7UHRZMZDStyia1ud3XDidSdBSt8J1ynnGu9ZBWSH0bA0le', 'Nueva Agencia', 'SuperAdmin', 1, 1);

-- 3. Plantilla de Ficha de la Nueva Agencia (en blanco lista para configurar)
INSERT INTO `agencias` (`id`, `nombre`, `razon_social`, `rfc`, `direccion`, `encargado_sistemas`, `telefono_sistemas`, `correo_sistemas`, `logo_url`, `foto_url`, `maps_url`) VALUES
(1, 'Nueva Agencia', 'Razón Social de la Agencia S.A. de C.V.', 'XAXX010101000', 'Dirección de la nueva agencia...', 'Encargado de Sistemas', '55 0000 0000', 'sistemas@agencia.com', '', '', '');

-- 4. Áreas departamentales estándar de agencia
INSERT INTO `agencia_areas` (`id`, `agencia_id`, `nombre`, `estatus`) VALUES
(1, 1, 'Administración', 1),
(2, 1, 'Sistemas', 1),
(3, 1, 'Ventas', 1),
(4, 1, 'Servicio', 1),
(5, 1, 'Refacciones', 1);

SET FOREIGN_KEY_CHECKS = 1;