-- =============================================
-- ESQUEMA MYSQL PARA EL MÓDULO DE INVENTARIO DE EQUIPOS
-- Portal de Sistemas - Grupo Huerta
-- =============================================

-- 1. Inventario Equipos VW
CREATE TABLE IF NOT EXISTS `inv_equipos_vw` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `departamento` VARCHAR(100),
  `puesto` VARCHAR(100),
  `usuario` VARCHAR(100),
  `nombre_equipo` VARCHAR(100),
  `estado` VARCHAR(50) DEFAULT 'Activo',
  `tipo_equipo` ENUM('Desktop', 'Laptop') DEFAULT 'Desktop',
  `expediente_completo` VARCHAR(50) DEFAULT 'No',
  `dominio` VARCHAR(100),
  `logmein` VARCHAR(100),
  `serie` VARCHAR(100),
  `dd` VARCHAR(50),
  `procesador` VARCHAR(100),
  `ghz` VARCHAR(50),
  `ram` VARCHAR(50),
  `direccion_mac` VARCHAR(50),
  `mac_wifi` VARCHAR(50),
  `mac_ethernet` VARCHAR(50),
  `sistema_op` VARCHAR(100),
  `fecha_compra` DATE,
  `folio_factura` VARCHAR(100),
  `inicio_garantia` DATE,
  `fin_garantia` DATE,
  `garantia2` VARCHAR(100),
  `renovacion_equipo` VARCHAR(100),
  `usuario_equipo_dominio` VARCHAR(100),
  `contrasena` VARCHAR(100),
  `office` VARCHAR(100),
  `serie_office` VARCHAR(100),
  `clave_candado` VARCHAR(100),
  `gds` VARCHAR(100),
  `por_usuario` VARCHAR(100),
  `equipo` VARCHAR(100),
  `remoto` VARCHAR(100),
  `usuario_gds` VARCHAR(100),
  `correo` VARCHAR(150),
  `correo_oficial_vw` VARCHAR(150),
  `correo_oficial_seat` VARCHAR(150),
  `extension` VARCHAR(50),
  `power_pb` VARCHAR(100),
  `contrasena_pb` VARCHAR(100),
  `poc` VARCHAR(100),
  `contrasena_poc` VARCHAR(100),
  `msqp` VARCHAR(100),
  `contrasena_msqp` VARCHAR(100),
  `grp` VARCHAR(100),
  `contrasena_grp` VARCHAR(100),
  `etka` VARCHAR(100),
  `contrasena_etka` VARCHAR(100),
  `facebook` VARCHAR(100),
  `contrasena_facebook` VARCHAR(100),
  `instagram` VARCHAR(100),
  `contrasena_instagram` VARCHAR(100),
  `wish` VARCHAR(100),
  `contrasena_wish` VARCHAR(100),
  `marketing_cloud` VARCHAR(100),
  `contrasena_marketing_cloud` VARCHAR(100),
  `sales_cloud_force` VARCHAR(100),
  `contrasena_sales_cloud_force` VARCHAR(100),
  `pagina_la_villa` VARCHAR(100),
  `contrasena_pagina_la_villa` VARCHAR(100),
  `urban_science` VARCHAR(100),
  `contrasena_urban_science` VARCHAR(100),
  `canva` VARCHAR(100),
  `contrasena_canva` VARCHAR(100),
  `cuenta_integral` VARCHAR(100),
  `contrasena_cuenta_integral` VARCHAR(100),
  `compra` VARCHAR(100),
  `proveedor` VARCHAR(100),
  `antivirus` VARCHAR(100),
  `dia_respaldo` VARCHAR(50),
  `hora_respaldo` VARCHAR(50),
  `no_break` VARCHAR(100),
  `modelo_nobreak` VARCHAR(100),
  `serie_nobreak` VARCHAR(100),
  `columna1` TEXT,
  `columna2` TEXT,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Equipos Baja
CREATE TABLE IF NOT EXISTS `inv_equipos_baja` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `departamento` VARCHAR(100),
  `puesto` VARCHAR(100),
  `usuario` VARCHAR(100),
  `nombre_equipo` VARCHAR(100),
  `estado` VARCHAR(50) DEFAULT 'Baja',
  `tipo_equipo` ENUM('Desktop', 'Laptop') DEFAULT 'Desktop',
  `dominio` VARCHAR(100),
  `logmein` VARCHAR(100),
  `serie` VARCHAR(100),
  `dd` VARCHAR(50),
  `procesador` VARCHAR(100),
  `ghz` VARCHAR(50),
  `ram` VARCHAR(50),
  `direccion_mac` VARCHAR(50),
  `mac_wifi` VARCHAR(50),
  `mac_ethernet` VARCHAR(50),
  `sistema_op` VARCHAR(100),
  `fecha_compra` DATE,
  `folio_factura` VARCHAR(100),
  `inicio_garantia` DATE,
  `fin_garantia` DATE,
  `garantia` VARCHAR(100),
  `renovacion_equipo` VARCHAR(100),
  `usuario_equipo` VARCHAR(100),
  `contrasena` VARCHAR(100),
  `office` VARCHAR(100),
  `serie_office` VARCHAR(100),
  `clave_candado` VARCHAR(100),
  `gds` VARCHAR(100),
  `correo` VARCHAR(150),
  `correo_oficial_vw` VARCHAR(150),
  `correo_oficial_seat` VARCHAR(150),
  `extension` VARCHAR(50),
  `compra` VARCHAR(100),
  `proveedor` VARCHAR(100),
  `antivirus` VARCHAR(100),
  `dia_respaldo` VARCHAR(50),
  `hora_respaldo` VARCHAR(50),
  `no_break` VARCHAR(100),
  `modelo_nobreak` VARCHAR(100),
  `serie_nobreak` VARCHAR(100),
  `expediente_completo` VARCHAR(50),
  `columna1` TEXT,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Nobreak BAJA
CREATE TABLE IF NOT EXISTS `inv_nobreak_baja` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `departamento` VARCHAR(100),
  `puesto` VARCHAR(100),
  `usuario` VARCHAR(100),
  `nombre_equipo` VARCHAR(100),
  `estado` VARCHAR(50) DEFAULT 'Baja',
  `modelo` VARCHAR(100),
  `serie_equipo` VARCHAR(100),
  `modelo_nobreak` VARCHAR(100),
  `serie_nobreak` VARCHAR(100),
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. Equipos Corporativo
CREATE TABLE IF NOT EXISTS `inv_equipos_corp` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `departamento` VARCHAR(100),
  `puesto` VARCHAR(100),
  `usuario` VARCHAR(100),
  `nombre_equipo` VARCHAR(100),
  `estado` VARCHAR(50) DEFAULT 'Activo',
  `tipo_equipo` ENUM('Desktop', 'Laptop') DEFAULT 'Desktop',
  `dominio` VARCHAR(100),
  `logmein` VARCHAR(100),
  `serie` VARCHAR(100),
  `dd` VARCHAR(50),
  `procesador` VARCHAR(100),
  `ghz` VARCHAR(50),
  `ram` VARCHAR(50),
  `direccion_mac` VARCHAR(50),
  `mac_wifi` VARCHAR(50),
  `mac_ethernet` VARCHAR(50),
  `sistema_op` VARCHAR(100),
  `fecha_compra` DATE,
  `folio_factura` VARCHAR(100),
  `inicio_garantia` DATE,
  `fin_garantia` DATE,
  `garantia` VARCHAR(100),
  `renovacion_equipo` VARCHAR(100),
  `usuario_equipo` VARCHAR(100),
  `contrasena` VARCHAR(100),
  `office` VARCHAR(100),
  `serie_office` VARCHAR(100),
  `clave_candado` VARCHAR(100),
  `gds` VARCHAR(100),
  `correo` VARCHAR(150),
  `correo_oficial_vw` VARCHAR(150),
  `correo_oficial_seat` VARCHAR(150),
  `extension` VARCHAR(50),
  `compra` VARCHAR(100),
  `proveedor` VARCHAR(100),
  `antivirus` VARCHAR(100),
  `dia_respaldo` VARCHAR(50),
  `hora_respaldo` VARCHAR(50),
  `no_break` VARCHAR(100),
  `modelo_nobreak` VARCHAR(100),
  `serie_nobreak` VARCHAR(100),
  `expediente_completo` VARCHAR(50),
  `columna1` TEXT,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. Celulares-Tablets - Pantallas
CREATE TABLE IF NOT EXISTS `inv_dispositivos_moviles` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `departamento` VARCHAR(100),
  `puesto` VARCHAR(100),
  `nombre` VARCHAR(100),
  `tablet` VARCHAR(100),
  `celular` VARCHAR(100),
  `pantalla` VARCHAR(100),
  `contrasena` VARCHAR(100),
  `serie` VARCHAR(100),
  `rom` VARCHAR(50),
  `ram` VARCHAR(50),
  `android` VARCHAR(50),
  `mail` VARCHAR(150),
  `mac` VARCHAR(50),
  `plan` VARCHAR(100),
  `factura` VARCHAR(100),
  `fecha_compra` DATE,
  `proveedor` VARCHAR(100),
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. Archivo
CREATE TABLE IF NOT EXISTS `inv_archivo` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `departamento` VARCHAR(100),
  `puesto` VARCHAR(100),
  `nombre` VARCHAR(100),
  `monitor` VARCHAR(100),
  `pulgadas` VARCHAR(50),
  `serie` VARCHAR(100),
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. Monitores
CREATE TABLE IF NOT EXISTS `inv_monitores` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `departamento` VARCHAR(100),
  `puesto` VARCHAR(100),
  `nombre` VARCHAR(100),
  `monitor` VARCHAR(100),
  `pulgadas` VARCHAR(50),
  `serie` VARCHAR(100),
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. DVR / Cámaras
CREATE TABLE IF NOT EXISTS `inv_dvr_camaras` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `camaras` VARCHAR(100),
  `dvr` VARCHAR(100),
  `ip` VARCHAR(50),
  `numero_serie` VARCHAR(100),
  `almacenamiento` VARCHAR(100),
  `contrasena_dvr` VARCHAR(100),
  `contrasena_camara` VARCHAR(100),
  `cam_totales_ip` INT DEFAULT 0,
  `disponibles_ip` INT DEFAULT 0,
  `cam_totales_analogicas` INT DEFAULT 0,
  `disponibles` INT DEFAULT 0,
  `modelo` VARCHAR(100),
  `nombre` VARCHAR(100),
  `capacidad_actual` VARCHAR(100),
  `cotizar` VARCHAR(100),
  `maximo_por_disco` VARCHAR(100),
  `capacidad_discos` VARCHAR(100),
  `tiene_actual` VARCHAR(100),
  `columna1` TEXT,
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 9. Inventario SITE VW
CREATE TABLE IF NOT EXISTS `inv_site_vw` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `departamento` VARCHAR(100),
  `puesto` VARCHAR(100),
  `usuario` VARCHAR(100),
  `nombre_equipo` VARCHAR(100),
  `estado` VARCHAR(50) DEFAULT 'Activo',
  `equipo` VARCHAR(100),
  `modelo` VARCHAR(100),
  `serie` VARCHAR(100),
  `fecha_compra` DATE,
  `folio_factura` VARCHAR(100),
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 10. Licencias Office
CREATE TABLE IF NOT EXISTS `inv_licencias_office` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `licencia` VARCHAR(100),
  `area` VARCHAR(100),
  `puesto` VARCHAR(100),
  `nombre` VARCHAR(100),
  `serie_equipo` VARCHAR(100),
  `nombre_equipo` VARCHAR(100),
  `serie_licencia` VARCHAR(100),
  `factura` VARCHAR(100),
  `actualizado_en` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
